### ISSUE TITLE
Problem With Loading bert_tone_model

### ISSUE THREAD

**Issue by sebsebar** [alexandrainst/danlp#101]
Hi! I've gotten this issue whilst trying to use the Bert Tone Model in Google Colab - I have installed all the required packages, and I've basically just tried to load the model :))
![Help](https://user-images.githubusercontent.com/43167725/100341028-54fb5480-2fdc-11eb-88f3-03e55bc0de21.jpg)

**Comment by AmaliePauli** [comment]
Hi @sebsebar, 
Sorry for the response time!  I tried to run it in Google Colab, and I got the same error as you . I recently updated the transformer version, but I am unsure why the danlp package work when the whole list of requirements is installed, but not when it is only the transformer version like in Google Colab.  None the less, I fixed this in bf48772  by changing the transformer version. I  testet the benchmark of the models and it stays the same. 

So In google colab, it should work to install  (for running the bert models):
!pip install transformers==3.1.0
!pip install git+https://github.com/alexandrainst/danlp.git
!pip install gensim==3.8.1

Let me know if it works for you now or if you have other questions?

Amalie

**Comment by sebsebar** [comment]
Ahh this is great Amalie! <3
And yes, actually I do have another question! Is there an easy way to get
the best model to run on a Colab GPU? I tried fiddling around with the
code, but I'm not sure it's actually running on the GPU :))

Best Wishes, Sebastian

**Comment by sebsebar** [comment]
Hi Amalie!
I'm sitting with the Bert Tone model, and your trick worked to get it
loaded into Colab. But, I'm having trouble running the model row-wise on my
huge data frame (*Error message:"UserWarning: Maximum length for sequence
exceeded..."*). Do you have a nice script for computing the sentiment
scores fast on a big data frame without exceeding the sequence length? :))

BIG hugs,
Sebastian

**Comment by sebsebar** [comment]
Moreover, is there a way to get the model to run on the GPU? :))

**Comment by AmaliePauli** [comment]
Hi :) 
The model is only built for text which is shorter than 512 tokens (by Berts's tokenizer), however, the code allows for more tokens, and this gives the warning. So if your text in each row is too long it is recommended to split the text in smaller chunks and run the Bert tone model on each chunk - It is not tested how well the model performance on longer text than this relatively small paragraphs of under 512 tokens. (Well yeah and then you properly have to combine the score again somehow if you need it row wise.) For splitting up your text, you can perhaps split into sentences (this can be done with spaCy), but after what kind your text is, that might be a better way to split your text into larger chunks (since too small chunks will require you to run the model a lot more times). If you dataframe is pandas, you can use the map function to predict each text row wise, but other than that I have no tip to make it run faster with the current code. I will open an issue of the need  to specify GPU use.  

Kind regard 
Amalie
