### ISSUE TITLE
load_with_spacy() in wiki_ann.py returns a total of 10 sentences 

### ISSUE THREAD

**Issue by Lasmali** [alexandrainst/danlp#13]
Is there a reason why most of the data from WikiAnn is excluded here?

https://github.com/alexandrainst/danlp/blob/2877bd0ce3494c2478657034f9b0ea9546bbe51b/danlp/datasets/wiki_ann.py#L49

Instead of having 95.930 sentences it returns a GoldCorpus with 10 sentences.

**Comment by hvingelby** [comment]
Hi @Lasmali,

I tried to replicate this problem by removing the downloaded dataset folder `~/.danlp/wikiann` and then setting a breakpoint on line 50 to see the length of `all_sents`. I found the length to be 95924.

Have you tried clearing the wikiann dataset folder?

**Comment by hvingelby** [comment]
I tried it out with spaCy v2.1.4 and after upgrading my spaCy version i also get the 10 sentences as you mention. 
In order to catch this earlier I think our requirements.txt should fetch the newest versions of the libraries so that we would detect this with CI.

I agree that we should not rely on sklearn for this. However I believe we would have to perform the dev/train because otherwise we would not be able to instantiate the GoldCorpus. One solution would be to make the user pass a splitting function and set a simple default one that does not depend on any other framework. What do you think of this solution?
