### ISSUE TITLE
Try out the Sentida sentiment tool

### ISSUE THREAD

**Issue by hvingelby** [alexandrainst/danlp#20]
A new Danish sentiment analysis tool has been released for R:
https://github.com/Guscode/Sentida

It would be nice to see how it compares to AFINN.

**Comment by AmaliePauli** [comment]
Add small sentiment test set from twitter with sentiment to benchmark  models.

**Comment by jacdals97** [comment]
I realize this issue was opened long ago and is now closed but hopefully you'll see this @hvingelby and @AmaliePauli 

Being one of the co-creators of Sentida, we compared Sentida against AFINN for an exam project and found that on a binary classification task on Truspilot reviews Sentida had 81% accuracy while AFINN had an accuracy of 74,5%.

The details of the tool and our benchmarking are described in this article

https://tidsskrift.dk/lwo/article/view/115711

**Comment by AmaliePauli** [comment]
Hi @jacdals97 
Thanks for your comment.
Nice that you have benchmarked the two systems as well, I updated docs to link to your paper. 
If you are doing more work on Danish sentiment you are welcome to contact us for a chat!

Amalie
