### ISSUE TITLE
Unknown keyword argument error in Flair part of speech tagging example

### ISSUE THREAD

**Issue by JensMadsen** [alexandrainst/danlp#69]
The example [here](https://github.com/alexandrainst/danlp/blob/master/docs/models/pos.md), throws an error because the flair `predict` method in the `[SequenceTagger](https://github.com/flairNLP/flair/blob/6b69d1d5eb0e3d30c42dd7de2a73e6dc9c97a251/flair/models/sequence_tagger_model.py#L299)` class has no `use_tokenizer` keyword argument. Not sure if the `use_tokenizer` argument is important? if not it could simply be removed :-)

**Comment by AmaliePauli** [comment]
Thanks for the comments, and sorry for the response time. I do not get the error, but I believe it is because danlp use an older version of flair==0.4.5 - But with this said, the tonkinizer in flair is not reaaly working as anticipated, so I will just remove the argument from the docs, however it is important to tokinze the sentences before hand, but for this I think spacy works well

**Comment by AmaliePauli** [comment]
Fix 9c44202
